In [9]:
import numpy as np
#start from 1 to 11*12, not including 11*12+1
tstArr = np.array(range(1, 11*12+1)).reshape(11,12)
print(tstArr)
#100th element is actually 99th one if we start from 0
np.unravel_index(100,(11,12))

[[  1   2   3   4   5   6   7   8   9  10  11  12]
 [ 13  14  15  16  17  18  19  20  21  22  23  24]
 [ 25  26  27  28  29  30  31  32  33  34  35  36]
 [ 37  38  39  40  41  42  43  44  45  46  47  48]
 [ 49  50  51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70  71  72]
 [ 73  74  75  76  77  78  79  80  81  82  83  84]
 [ 85  86  87  88  89  90  91  92  93  94  95  96]
 [ 97  98  99 100 101 102 103 104 105 106 107 108]
 [109 110 111 112 113 114 115 116 117 118 119 120]
 [121 122 123 124 125 126 127 128 129 130 131 132]]


(8, 4)

In [10]:
 twobyfour = [
   [0,1,2,3], 
   [4,5,6,7]
]

In [11]:
np.unravel_index([0,7], (2,4))

(array([0, 1], dtype=int64), array([0, 3], dtype=int64))

In [35]:
import sys
a = np.array([[4, 3, 1], [5, 7, 0], [9, 9, 3], [8, 2, 4]])
print(a)

[[4 3 1]
 [5 7 0]
 [9 9 3]
 [8 2 4]]


In [34]:


temp = a[:,0]
print(temp)
a[0,:] = a[2,:]
a[2,:] = temp
# Write your code for swapping here

# Print the array after swapping
print(a)

[1 0 3 4]


ValueError: could not broadcast input array from shape (4) into shape (3)

In [38]:
x = np.ones((3,3))
print("Original array:")
print(x)
print("1 on the border and 0 inside in the array")
x[1:-1,1:-1] = 0
print(x)


Original array:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
1 on the border and 0 inside in the array
[[1. 1. 1.]
 [1. 0. 1.]
 [1. 1. 1.]]
